version: "3.7"

services:
    db:
        build:
            context: .
            dockerfile: Dockerfile.db
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=secret

    app:
        build: .
        depends_on:
            - db
        environment:
            - PORT=8080
        ports:
            - 8080:8080
